Commands:
    BaseCommand: sorteio
    Create: criar
    Buy: comprar
    Cancel: cancelar
    List: listar
    GUI: gui
Options:
    Cost: 100.0
    MessagesFile: Messages.yml
    BroadcastWin: false
    BlockedItems:
        - 1
        - 2
        - 3:1
